INSERT INTO USER (ID, USER_ID, PASSWORD, USER_NAME, EMAIL) VALUES (1, 'yaja', 'test', 'Jacob', 'yaja@test.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, USER_NAME, EMAIL) VALUES (2, 'momo', 'test', 'Momo', 'momo@test.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, USER_NAME, EMAIL) VALUES (3, 'test', 'test', 'Test', 'momo@test.com');

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (1, 1, 'TEST YAJA', 'TEST TEST TEST123 YAJA', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (2, 2, 'TEST MOMO', 'TEST TEST TEST123 MOMO', CURRENT_TIMESTAMP());